name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.0.1)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate version exists
        run: |
          VERSION=${{ github.event.inputs.version }}
          if ! curl --fail -s https://hub.docker.com/v2/repositories/prajguru54/chat-client/tags/${VERSION}/ > /dev/null; then
            echo "Version ${VERSION} not found in Docker registry"
            exit 1
          fi
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.PROD_SERVER }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Deploy specific version
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }} "
            cd /opt/chat-app && \
            export VERSION=${{ github.event.inputs.version }} && \
            docker-compose -f docker-compose.prod.yml pull && \
            docker-compose -f docker-compose.prod.yml up -d
          "

      - name: Health check
        run: |
          sleep 10
          curl --fail http://${{ secrets.PROD_SERVER }}:5173
          curl --fail http://${{ secrets.PROD_SERVER }}:3000/health