name: Production Release

on:
  push:
    branches:
      - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get version from branch name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: github-changelog-generator/github-changelog-generator@v1.16.4
        with:
          futureRelease: ${{ env.VERSION }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-client:${{ env.VERSION }}
            
      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: New Release v${{ env.VERSION }} Published
          body: |
            A new version v${{ env.VERSION }} has been released.
            
            See changelog for details: 
            ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ env.VERSION }}
          to: team@yourdomain.com
          from: GitHub Actions
